services:
  project-db:
    container_name: project-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: spring_boot_app
    ports:
      - "5332:5432"
    volumes:
      - postgres_data:/data/postgresql
    networks:
      - postgres
volumes:
  postgres_data:
networks:
  postgres:
    driver: bridge